"""added imsmall storage key to Image

Revision ID: 342ff926c403
Revises: a4c51ecd7cb1
Create Date: 2026-05-07 22:23:37.395643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342ff926c403'
down_revision = 'a4c51ecd7cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key_small', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('storage_key_small')

    # ### end Alembic commands ###
