"""Added purpose columns to images

Revision ID: 4e0b256938fb
Revises: 342ff926c403
Create Date: 2026-05-09 18:54:33.560970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0b256938fb'
down_revision = '342ff926c403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_img', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hero_img', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('hero_img')
        batch_op.drop_column('portfolio_img')

    # ### end Alembic commands ###
